#!/usr/bin/env groovy

pipeline {
    agent any

    tools {
        go 'go-1.17'
    }

    environment {
        //Github Parameter
        COMPANY_NAME = "alvintzz"
        REPOSITORY_NAME = "testapp"
        BRANCH_NAME = "main"
        BINARY_DIR = "cmd/hello-world"
        
        // Golang Parameter
        GO111MODULE = 'on'

        REPOSITORY_DIR = "~/go/src/github.com/$COMPANY_NAME/$REPOSITORY_NAME"
    }

    stages {
        stage('Pull Code from Github') {
            steps {
                dir("${env.REPOSITORY_DIR}") {
                    git branch: "${env.BRANCH_NAME}", url: "https://github.com/${env.COMPANY_NAME}/${env.REPOSITORY_NAME}.git"
                }
            }
        }

        stage('Building') {
            steps {
                dir("${env.REPOSITORY_DIR}") {
                    sh "go build -o ${env.REPOSITORY_NAME} ./${env.BINARY_DIR}"
                }
            }
        }

        stage('Running Unit Test') {
            steps {
                dir("${env.REPOSITORY_DIR}") {
                    sh 'go test ./... -race -cover'
                }
            }
        }

        stage('Just Print something') {
            steps {
                echo 'Just Print something here.'
            }
        }
    }

    post {
        success {
            echo 'Pipeline Success'
        }

        failure {
            echo 'Pipeline Failed'
        }
    }
}