#!/usr/bin/env groovy

pipeline {
    agent any

    environment {
        REPOSITORY_NAME = "testapp"
        BRANCH_NAME = "main"
        REPOSITORY_DIR = "~/go/src/github.com/alvintzz/$REPOSITORY_NAME"
    }

    stages {
        stage('Pull Code from Github') {
            steps {
                dir("${env.REPOSITORY_DIR}") {
                    git branch: "${env.BRANCH_NAME}", url: "https://github.com/tokopedia/${env.REPOSITORY_NAME}.git"
                }
            }
        }

        stage('Just Print something') {
            steps {
                echo 'Just Print something here.'
            }
        }
    }

    post {
        success {
            echo 'Pipeline Success'
        }

        failure {
            echo 'Pipeline Failed'
        }
    }
}